[package]
name = "sirius-telemetry-server"
version.workspace = true
edition.workspace = true

[features]
ui = ["quent-query-engine-server/ui"]
swagger = ["quent-query-engine-server/swagger"]

[dependencies]
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
instrumentation-model = { path = "../model", features = ["collector"] }
sirius-telemetry-analyzer = { path = "../analyzer" }
nvtx-server = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
quent-collector = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
quent-io = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
quent-query-engine-server = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
tracing = "0.1"
uuid = "1"

[build-dependencies]
quent-simulator-ui = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
quent-query-engine-ui = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
quent-ui = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
ts-rs = { version = "12", features = ["uuid-impl", "serde-json-impl"] }
