[package]
name = "telemetry-bridge"
version.workspace = true
edition.workspace = true

[lib]
name = "telemetry_bridge"
crate-type = ["staticlib"]

[dependencies]
cxx = "1"
instrumentation-model = { path = "../model" }
nvtx-bridge = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
nvtx-injection = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1", features = ["static-injection"] }

[build-dependencies]
cxx-build = "1"
instrumentation-model = { path = "../model" }
quent-codegen = { git = "https://github.com/rapidsai/quent.git", rev = "b21933d06dbb0c46339ded31d0fdaacae03cc3b1" }
