# cmake-format: off
set(TEST_SOURCES
    test/cpp/scan/test_native_physical_matrix.cpp
    test/cpp/scan/test_parquet_physical_profile.cpp
    test/cpp/scan/test_scan_planning_measurements.cpp
    test/cpp/scan/test_native_checkpoint_lease.cpp
    test/cpp/transparent/test_read_view_comparison.cpp
    test/cpp/integration/test_transparent_read_view.cpp
    test/cpp/scan/test_split_certificates.cpp
    test/cpp/transparent/test_late_failure.cpp
    test/cpp/transparent/test_plan_source_policy.cpp
    test/cpp/scan/test_scan_contracts.cpp
    test/cpp/scan/test_scan_verdicts.cpp
    test/cpp/integration/test_transparent_verdicts.cpp
    test/cpp/compression/test_compression.cpp
    test/cpp/config/test_config.cpp
    test/cpp/config/test_context.cpp
    test/cpp/config/test_object_store_config.cpp
    test/cpp/config/test_topology_config.cpp
    test/cpp/creator/test_task_creator_query_state.cpp
    test/cpp/creator/test_task_creator_schedule_validation.cpp
    test/cpp/data/test_chunked_spill_copy.cpp
    test/cpp/data/test_convertible_data_batch.cpp
    test/cpp/data/test_spill_converter_ordering.cpp
    test/cpp/data/test_data_repository_manager_registry.cpp
    test/cpp/data/test_convertible_gpu_pipeline_task.cpp
    test/cpp/downgrade/test_downgrade_disk.cpp
    test/cpp/creator/test_task_creator.cpp
    test/cpp/downgrade/test_downgrade_executor.cpp
    test/cpp/downgrade/test_downgrade_lifecycle.cpp
    test/cpp/downgrade/test_spill_policy.cpp
    test/cpp/exec/test_batch_stream.cpp
    test/cpp/exec/test_bounded_thread_pool.cpp
    test/cpp/exec/test_inspectable_mpsc.cpp
    test/cpp/exec/test_interruptible_mpmc.cpp
    test/cpp/exec/test_multi_index_priority_queue.cpp
    test/cpp/event/test_query_event_publisher.cpp
    test/cpp/exec/test_semi_future.cpp
    test/cpp/exec/test_sirius_ffi_fragment.cpp
    test/cpp/exec/test_stream_bind_catalog.cpp
    test/cpp/exec/test_cuda_event_completion_poll.cpp
    test/cpp/exec/test_stream_session.cpp
    test/cpp/exec/test_streaming_fragment.cpp
    test/cpp/exec/test_thread_util.cpp
    test/cpp/expression/test_ast_aggregate.cpp
    test/cpp/expression/test_ast_clone.cpp
    test/cpp/expression/test_ast_substitute.cpp
    test/cpp/expression/test_ast_from_duckdb.cpp
    test/cpp/expression/test_ast_scaffold.cpp
    test/cpp/expression/test_ast_to_duckdb.cpp
    test/cpp/expression/test_comparison_type_mapping.cpp
    test/cpp/expression/test_function_id.cpp
    test/cpp/expression/test_value.cpp
    test/cpp/expression_evaluator/test_expression_evaluator.cpp
    test/cpp/expression_evaluator/test_expression_evaluator_ast_equivalence.cpp
    test/cpp/expression_evaluator/test_gpu_expression_translator.cpp
    test/cpp/expression_evaluator/test_like_multiliteral.cpp
    test/cpp/expression_evaluator/test_nonduckdb_frontend_proof.cpp
    test/cpp/helper/test_cudf_utils.cpp
    test/cpp/helper/test_logical_type.cpp
    test/cpp/helper/test_numeric_narrowing.cpp
    test/cpp/helper/test_transaction_utils.cpp
    test/cpp/integration/test_compressed_materialization_gate.cpp
    test/cpp/integration/test_compressed_materialization_partition.cpp
    test/cpp/integration/test_gpu_execution_aggregate_nulls.cpp
    test/cpp/integration/test_gpu_execution_allnull_scan.cpp
    test/cpp/integration/test_gpu_execution_array.cpp
    test/cpp/integration/test_gpu_execution_cast_date_predicates.cpp
    test/cpp/integration/test_gpu_execution_dense_count_join.cpp
    test/cpp/integration/test_gpu_execution_dynamic_filter_native.cpp
    test/cpp/integration/test_gpu_execution_dynamic_filter_sip.cpp
    test/cpp/integration/test_gpu_execution_filter_nulls.cpp
    test/cpp/integration/test_gpu_execution_join_nulls.cpp
    test/cpp/integration/test_gpu_execution_locality.cpp
    test/cpp/integration/test_gpu_execution_multi_format.cpp
    test/cpp/integration/test_gpu_execution_null_safe_join.cpp
    test/cpp/integration/test_gpu_execution_order_nulls.cpp
    test/cpp/integration/test_gpu_execution_size_estimation.cpp
    test/cpp/integration/test_gpu_execution_parquet_nulls.cpp
    test/cpp/integration/test_gpu_execution_semantic_cast_fallback.cpp
    test/cpp/integration/test_gpu_execution_setting_scope.cpp
    test/cpp/integration/test_parquet_null_predicate_pushdown.cpp
    test/cpp/integration/test_query_lifecycle_slot.cpp
    test/cpp/integration/test_gpu_execution_tpcds_nulls.cpp
    test/cpp/integration/test_gpu_execution_tpch.cpp
    test/cpp/integration/test_gpu_execution_tpch_mgpu_audit.cpp
    test/cpp/integration/test_gpu_execution_unique_join.cpp
    test/cpp/integration/test_gpu_execution_union_all.cpp
    test/cpp/integration/test_gpu_execution_vector_search.cpp
    test/cpp/integration/test_pin_registry_epoch.cpp
    test/cpp/integration/test_pin_table_host_streaming.cpp
    test/cpp/integration/test_pin_table_merge_columns.cpp
    test/cpp/integration/test_pin_table_column_order.cpp
    test/cpp/integration/test_pin_table_mvcc_delete.cpp
    test/cpp/integration/test_pin_table_mvcc_foundation.cpp
    test/cpp/integration/test_pin_table_mvcc_insert.cpp
    test/cpp/integration/test_pin_table_mvcc_update.cpp
    test/cpp/integration/test_pin_table_type_drift.cpp
    test/cpp/integration/test_pin_table_zone_map_pruning.cpp
    test/cpp/integration/test_table_gpu_cache_warm_mgpu.cpp
    test/cpp/integration/test_transparent_provider_isolation.cpp
    test/cpp/integration/test_transparent_runtime_fallback.cpp
    test/cpp/late_mat/test_column_origin.cpp
    test/cpp/late_mat/test_prepared_selection.cpp
    test/cpp/late_mat/test_materialize.cpp
    test/cpp/late_mat/test_port_materialize.cpp
    test/cpp/integration/test_late_mat_deferred_query.cpp
    test/cpp/integration/test_late_mat_native_filter.cpp
    test/cpp/late_mat/test_defer_policy.cpp
    test/cpp/late_mat/test_defer_directive.cpp
    test/cpp/late_mat/test_late_mat_plan_pass.cpp
    test/cpp/late_mat/test_late_mat_resolver.cpp
    test/cpp/late_mat/test_pin_handle_lifecycle.cpp
    test/cpp/late_mat/test_pin_uniqueness.cpp
    test/cpp/io/s3/test_sigv4.cpp
    test/cpp/io/s3/test_s3_default_visibility_guard.cpp
    test/cpp/io/s3/test_sirius_sigv4_authorizer.cpp
    test/cpp/io/s3/test_static_credentials.cpp
    test/cpp/io/test_parquet_helpers.cpp
    test/cpp/io/test_uri_parser.cpp
    test/cpp/io/uring/test_uring_readv.cpp
    test/cpp/io/rest/test_rest_reactor.cpp
    test/cpp/log/test_duckdb_sink.cpp
    test/cpp/log/test_logging.cpp
    test/cpp/scan_manager/test_s3_routing_cutover.cpp
    test/cpp/scan_manager/test_pin_table_multi_gpu.cpp
    test/cpp/scan_manager/test_cached_serving_hardening.cpp
    test/cpp/scan_manager/test_insert_delta_job.cpp
    test/cpp/scan_manager/test_memory_prefetcher_accounting.cpp
    test/cpp/scan_manager/test_mvcc_mask_job.cpp
    test/cpp/scan_manager/test_pinned_chunk_stats.cpp
    test/cpp/scan_manager/test_pin_registry_epoch_mutations.cpp
    test/cpp/scan_manager/test_pinned_entry_column_lookup.cpp
    test/cpp/scan_manager/test_split_connector.cpp
    test/cpp/operator/test_physical_grouped_aggregate_merge_mgpu.cpp
    test/cpp/operator/test_physical_hash_join_mgpu.cpp
    test/cpp/operator/test_physical_order_mgpu.cpp
    test/cpp/operator/test_task_scheduler_routing.cpp
    test/cpp/operator/test_physical_union.cpp
    test/cpp/operator/test_physical_union_mgpu.cpp
    test/cpp/operator/test_partition_memspace_mgpu.cpp
    test/cpp/memory/test_multiple_blocks_allocation_accessor.cpp
    test/cpp/memory/test_topology_index.cpp
    test/cpp/operator/test_build_probe_scheduling.cpp
    test/cpp/operator/test_cross_schedule.cpp
    test/cpp/operator/aggregate/test_gpu_merge_impl.cpp
    test/cpp/operator/aggregate/test_group_key_labels.cpp
    test/cpp/operator/aggregate/test_physical_grouped_aggregate.cpp
    test/cpp/operator/aggregate/test_physical_grouped_aggregate_count_distinct.cpp
    test/cpp/operator/aggregate/test_physical_grouped_aggregate_merge.cpp
    test/cpp/operator/test_crc32_partition_hash.cpp
    test/cpp/operator/test_gpu_partition_impl.cpp
    test/cpp/operator/test_host_table_chunk_reader.cpp
    test/cpp/operator/test_physical_concat.cpp
    test/cpp/operator/test_physical_dense_count_join.cpp
    test/cpp/operator/test_physical_sort_sample.cpp
    test/cpp/operator/test_physical_filter.cpp
    test/cpp/operator/test_physical_limit.cpp
    test/cpp/operator/test_physical_mark_join.cpp
    test/cpp/operator/test_physical_merge_sort.cpp
    test/cpp/operator/test_physical_order.cpp
    test/cpp/operator/test_physical_partition.cpp
    test/cpp/operator/test_physical_projection.cpp
    test/cpp/operator/test_physical_result_collector.cpp
    test/cpp/operator/test_physical_streaming_sink.cpp
    test/cpp/operator/test_physical_streaming_source.cpp
    test/cpp/operator/test_physical_table_scan.cpp
    test/cpp/operator/test_no_history_peak_memory_estimate.cpp
    test/cpp/operator/test_physical_top_n.cpp
    test/cpp/operator/test_physical_ungrouped_aggregate.cpp
    test/cpp/operator/test_sirius_dynamic_filter.cpp
    test/cpp/operator/test_dynamic_filter_publication_claim.cpp
    test/cpp/operator/test_dynamic_filter_publisher.cpp
    test/cpp/operator/test_dynamic_filter_source_policy.cpp
    test/cpp/operator/test_sirius_dynamic_filter_mgpu.cpp
    test/cpp/parallel/test_task_executor.cpp
    src/planner/dynamic_filter/duckdb_join_filter_candidate_adapter.cpp
    test/cpp/planner/test_compressed_schema_propagation.cpp
    test/cpp/planner/test_dense_count_join_detection.cpp
    test/cpp/planner/test_gpu_admission.cpp
    test/cpp/planner/test_distinct_hash_join_detection.cpp
    test/cpp/planner/test_duckdb_join_filter_candidate_adapter.cpp
    test/cpp/planner/test_build_filter_evidence.cpp
    test/cpp/planner/test_build_key_domain.cpp
    test/cpp/planner/test_dynamic_filter_discovery_parity.cpp
    test/cpp/planner/test_dynamic_filter_key_admission.cpp
    test/cpp/planner/test_dynamic_filter_target_discovery.cpp
    test/cpp/planner/test_join_expression_key.cpp
    test/cpp/planner/test_plan_tree_shape.cpp
    test/cpp/planner/test_projection_fold.cpp
    test/cpp/planner/test_sirius_read_parquet_scan.cpp
    test/cpp/planner/test_query_id.cpp
    test/cpp/planner/test_query_index.cpp
    test/cpp/planner/test_tier_narrowing_policy.cpp
    test/cpp/pipeline/test_batch_lock_utils.cpp
    test/cpp/pipeline/test_completion_signal.cpp
    test/cpp/pipeline/test_gpu_pipeline_executor.cpp
    test/cpp/pipeline/test_oom_reschedule.cpp
    test/cpp/pipeline/test_pipeline_memory_history.cpp
    test/cpp/pipeline/test_data_size_estimator.cpp
    test/cpp/pipeline/test_gpu_pipeline_task_history.cpp
    test/cpp/pipeline/test_gpu_pipeline_disk_readback.cpp
    test/cpp/pipeline/test_get_next_ports_after_sink.cpp
    test/cpp/pipeline/test_merge_pipeline_fusion.cpp
    test/cpp/pipeline/test_partition_build_pipelines.cpp
    test/cpp/pipeline/test_pipeline_build_context.cpp
    test/cpp/pipeline/test_pipeline_dynamic_filter_native_shape.cpp
    test/cpp/pipeline/test_pipeline_schedule_canonical.cpp
    test/cpp/pipeline/test_per_query_completion_handler.cpp
    test/cpp/pipeline/test_plan_printer.cpp
    test/cpp/pipeline/test_repository_wiring_materializer.cpp
    test/cpp/pipeline/test_streaming_sink_root.cpp
    test/cpp/pipeline/test_task_index_keys.cpp
    test/cpp/pipeline/test_task_scheduler.cpp
    test/cpp/pipeline/test_union_build_pipelines.cpp
    test/cpp/scan/bench_decode_codecs.cpp
    test/cpp/scan/test_can_serve_with_columns.cpp
    test/cpp/scan/test_duckdb_block_layout.cpp
    test/cpp/scan/test_duckdb_insert_delta.cpp
    test/cpp/scan/test_duckdb_mvcc_visibility.cpp
    test/cpp/scan/test_duckdb_native_batch_coalescer.cpp
    test/cpp/scan/test_duckdb_native_deferred_walk.cpp
    test/cpp/scan/test_duckdb_native_dict_fsst.cpp
    test/cpp/scan/test_duckdb_native_empty_split_decode.cpp
    test/cpp/scan/test_duckdb_native_host_backed_decode.cpp
    test/cpp/scan/test_duckdb_native_walker.cpp
    test/cpp/scan/test_dynamic_filter_merge.cpp
    test/cpp/scan/test_iceberg_batch_layout.cpp
    test/cpp/scan/test_iceberg_equality_delete.cpp
    test/cpp/scan/test_puffin_reader.cpp
    test/cpp/scan/test_gpu_decode_alp.cpp
    test/cpp/scan/test_gpu_decode_bitpacking.cpp
    test/cpp/scan/test_gpu_decode_rle.cpp
    test/cpp/scan/test_gpu_decode_strings.cpp
    test/cpp/scan/test_host_keep_mask.cpp
    test/cpp/scan/test_gpu_native_decode.cpp
    test/cpp/scan/test_owning_table_view.cpp
    test/cpp/scan/test_parquet_schema_mapping.cpp
    test/cpp/scan/test_parquet_null_count_pruning.cpp
    test/cpp/scan/test_residual_filter.cpp
    test/cpp/scan/test_scan_filter_cast_ranges.cpp
    test/cpp/scan/test_scan_filter_ranges.cpp
    test/cpp/scan/test_parquet_scan_sizing.cpp
    test/cpp/scan/test_parquet_virtual_column_plan.cpp
    test/cpp/scan/test_scan_output_assembly.cpp
    test/cpp/scan/test_scan_schema_normalization.cpp
    test/cpp/scan/test_stream_lineage_item5.cpp
    test/cpp/sirius_extension/test_sirius_read_parquet_cardinality.cpp
    test/cpp/sql/test_sirius_sql_rewrite.cpp
    test/cpp/telemetry/test_telemetry_context.cpp
    test/cpp/vss/test_brute_force_search.cpp
    test/cpp/vss/test_cudf_raft_interop.cpp
    test/cpp/vss/test_cuvs_index_cache.cpp
    test/cpp/vss/test_distance_metric.cpp
    test/cpp/vss/test_enn_top_k.cpp
    test/cpp/vss/test_ivf_flat_index.cpp
    test/cpp/vss/test_pinned_column.cpp
    test/cpp/vss/test_vector_search.cpp
    test/cpp/unittest.cpp
    test/cpp/utils/pipeline_conversion_test_utils.cpp
    test/cpp/utils/sirius_test_env.cpp
    test/cpp/utils/test_child_process_environment.cpp
    test/cpp/utils/test_gpu_execution_comparator.cpp
    test/cpp/utils/utils.cpp)
# cmake-format: on

if(SIRIUS_LEGACY_TEST_SOURCES)
  list(APPEND TEST_SOURCES ${SIRIUS_LEGACY_TEST_SOURCES})
endif()

# The testcontainers-backed S3 harness only compiles when its dependency is
# built; unittest.cpp guards its use behind SIRIUS_HAVE_TESTCONTAINERS.
if(SIRIUS_BUILD_S3_TESTS)
  list(
    APPEND
    TEST_SOURCES
    test/cpp/utils/s3_container.cpp
    test/cpp/io/s3/test_sirius_httpfs.cpp
    test/cpp/io/rest/test_rest_ioctx_integration.cpp
    test/cpp/scan_manager/test_describe_parquet_s3.cpp
    test/cpp/integration/test_s3_sql_surface.cpp
    test/cpp/integration/test_s3_tpch.cpp)
endif()

# Orphaned test files (present in the tree but missing from TEST_SOURCES) are
# caught by the check-orphan-tests pre-commit hook
# (scripts/check_orphan_tests.py) rather than a configure-time glob — see
# test/cpp/orphan_test_allowlist.txt.
